notifications:
  email: false
dist: xenial   # required for Python >= 3.7
language: python
python:
  - '3.6'
  - '3.7'
branches:
  only:
  - development
os:
  - linux
install:
  - sudo apt-get install texlive-base
  - which pdflatex
  - ls /usr/bin/pdflatex
  - pip install regex jinja2 lxml python-slugify click pdfCropMargins
  - make install
script:
  - pytest