notifications:
  email: false
dist: xenial   # required for Python >= 3.7
language: python
python:
  - '3.6'
  - '3.7'
branches:
  only:
  - development
os:
  - linux
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra
    - pdf2svg
    - librsvg2-bin
    - asymptote
install:
  - pip install regex jinja2 lxml python-slugify click pdfCropMargins
  - make install
script:
  - pytest