notifications:
  email: false
dist: xenial   # required for Python >= 3.7
language: python
python:
  - '3.6'
  - '3.7'
branches:
  only:
  - development
os:
  - linux
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra  # provides 'enumitem'
    - texlive-fonts-recommended  # provides 'ecrm1200'
    - pdf2svg
    - librsvg2-bin
    - asymptote
install:
  - pip install regex jinja2 lxml python-slugify click pdfCropMargins sanic pytest-sanic
  - make install
script:
  - pytest