notifications:
  email: false
dist: focal   # required for Python >= 3.7
language: python
python:
  - '3.7'
  - '3.8'
  - '3.9'
branches:
  only:
  - development
os:
  - linux
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra  # provides 'enumitem'
    - texlive-fonts-recommended  # provides 'ecrm1200'
    - latexmk
    - pdf2svg
    - librsvg2-bin
    - asymptote
    update: true
before_install:
  - pip install --upgrade pip  # upgrade pip
install:
  - pip install ".[test]" . # install package + test dependencies
script:
  - pytest